// Fictional sample catalog: prices and specifications are demo data, in INR.
export const products = [
  {
    id: "p1",
    name: "Nova Everyday",
    category: "Phones",
    price: 14999,
    icon: "phone",
    color: "lavender",
    tagline: "Everything you need. Nothing extra.",
    features: ["128GB storage", "Long battery life", "5G connectivity"],
  },
  {
    id: "p2",
    name: "PixelPeak Camera",
    category: "Phones",
    price: 24999,
    icon: "phone",
    color: "peach",
    tagline: "For moments worth keeping.",
    features: ["256GB storage", "50MP camera", "Optical stabilization"],
  },
  {
    id: "p3",
    name: "Vertex Pro",
    category: "Phones",
    price: 54999,
    icon: "phone",
    color: "blue",
    tagline: "More power in your pocket.",
    features: ["512GB storage", "120Hz display", "Flagship gaming processor"],
  },
  {
    id: "p4",
    name: "QuietSpace 30",
    category: "Headphones",
    price: 4999,
    icon: "headphones",
    color: "sage",
    tagline: "A little less noise. A lot more focus.",
    features: [
      "Active noise cancellation",
      "30-hour battery",
      "Wireless Bluetooth",
    ],
  },
  {
    id: "p5",
    name: "StudioForm",
    category: "Headphones",
    price: 12999,
    icon: "headphones",
    color: "lavender",
    tagline: "Hear the details you were missing.",
    features: ["Wired connection", "Studio monitoring", "Over-ear comfort"],
  },
  {
    id: "p6",
    name: "Move Buds",
    category: "Headphones",
    price: 2499,
    icon: "buds",
    color: "peach",
    tagline: "Your everyday soundtrack.",
    features: [
      "Water resistant",
      "Lightweight earbuds",
      "Secure fit for workouts",
    ],
  },
  {
    id: "p7",
    name: "Daybook Air",
    category: "Laptops",
    price: 39999,
    icon: "laptop",
    color: "blue",
    tagline: "Light in your bag. Big on possibility.",
    features: ["8GB RAM", "256GB SSD", "Lightweight for students"],
  },
  {
    id: "p8",
    name: "Codebook 14",
    category: "Laptops",
    price: 64999,
    icon: "laptop",
    color: "sage",
    tagline: "Make room for your next big idea.",
    features: ["16GB RAM", "512GB SSD", "Great for programming"],
  },
  {
    id: "p9",
    name: "Forge Gaming",
    category: "Laptops",
    price: 99999,
    icon: "laptop",
    color: "lavender",
    tagline: "Built for the next level.",
    features: ["32GB RAM", "1TB SSD", "Dedicated gaming GPU"],
  },
  {
    id: "p10",
    name: "Pace Fit",
    category: "Watches",
    price: 2999,
    icon: "watch",
    color: "peach",
    tagline: "Small steps. Everyday progress.",
    features: ["Step tracking", "Heart rate sensor", "7-day battery"],
  },
  {
    id: "p11",
    name: "Trail GPS",
    category: "Watches",
    price: 7999,
    icon: "watch",
    color: "sage",
    tagline: "Take the scenic route.",
    features: ["Built-in GPS", "Water resistant", "Outdoor running modes"],
  },
  {
    id: "p12",
    name: "Orbit Smart",
    category: "Watches",
    price: 14999,
    icon: "watch",
    color: "blue",
    tagline: "Stay a little more connected.",
    features: ["Bluetooth calls", "AMOLED display", "Fitness tracking"],
  },
];
